# -*- coding: utf-8 -*-
"""A2_RESNET_FCNN_Image_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOeIORNbJJiX4FCJQvOjc8m7fVZoaZTK

Image CNN with transfer learning from RESNET and FCNN head for classification:

Structure/Workflow:

Image ->
RESNET (pretrained) ->
Global pooled features (1280-d) ->
Projection layer (optional, recommended) ->
Classifier head (FCNN)

Expected Folder Strucure(expand to read):

dataset_root/
├── train/
│   ├── Blue/
│   │   ├── image_001.jpg
│   │   ├── image_002.jpg
│   │   └── ...
│   ├── Green/
│   │   └── ...
│   ├── Black/
│   │   └── ...
│   └── Other/
│       └── ...
├── val/
│   ├── Blue/
│   ├── Green/
│   ├── Black/
│   └── Other/
└── test/
    ├── Blue/
    ├── Green/
    ├── Black/
    └── Other/

Imports
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import models, transforms
from torchvision.datasets import ImageFolder
import matplotlib.pyplot as plt
import os

"""Device Setup"""

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""Paths/Parameters/Settings definitions"""

BATCH_SIZE = 8
NUM_WORKERS = 2
NUM_CLASSES = 4
EPOCHS = 30
UNFREEZE_EPOCH = int(0.8*EPOCHS)
INITIAL_LR = 1e-3
FINE_TUNE_LR = 1e-5
SAVE_MODEL_PATH = "/home/le.song/Assignment2/best_image_model.pth"
MISCLASS_FILE = "/home/le.song/Assignment2/misclassified.txt"
LOSS_PLOT_PATH = "/home/le.song/Assignment2/loss_curve.png"
TRAIN_PATH = "/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Train"
VAL_PATH = "/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Val"
TEST_PATH = "/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Test"

"""Data Transforms"""

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2), #Optional, will monitor effects.
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])])  #Stats need to align with that of resnet, no stat calculations needed on input data.

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),  #Testing data MUST NOT be pre-processed. No rotations/flips/jitter applied.
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

""" Datasets and Data-Loaders"""

import shutil # Added for removing directories

def remove_ipynb_checkpoints(root_dir):
    if not os.path.exists(root_dir):
        print(f"Warning: Root directory {root_dir} does not exist. Skipping cleanup.")
        return
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if '.ipynb_checkpoints' in dirnames:
            checkpoints_path = os.path.join(dirpath, '.ipynb_checkpoints')
            print(f"Removing .ipynb_checkpoints directory: {checkpoints_path}")
            shutil.rmtree(checkpoints_path)
            # Remove from dirnames so os.walk doesn't try to enter it after deletion
            dirnames.remove('.ipynb_checkpoints')

# Applied as cleanup before creating ImageFolder datasets
remove_ipynb_checkpoints(TRAIN_PATH)
remove_ipynb_checkpoints(VAL_PATH)
remove_ipynb_checkpoints(TEST_PATH)

train_dataset = ImageFolder(root=TRAIN_PATH, transform=train_transform)
val_dataset = ImageFolder(root=VAL_PATH, transform=test_transform) #this one doesn't augment
test_dataset = ImageFolder(root=TEST_PATH, transform=test_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

#Verifying sizes/dimension
print("Train samples:", len(train_dataset))
print("Val samples:", len(val_dataset))
print("Test samples:", len(test_dataset))

"""RESNET Image Encoder Definition"""

import torch
import torch.nn as nn
import torchvision.models as models

class ImageEncoder(nn.Module):
    def __init__(self, pretrained=True, freeze_backbone=True, proj_dim=256):
        super().__init__()

        # Load pretrained ResNet50
        self.backbone = models.resnet50(
            weights=models.ResNet50_Weights.DEFAULT if pretrained else None
        )

        # Remove final classification layer
        self.feature_dim = self.backbone.fc.in_features  # 2048 for ResNet50
        self.backbone.fc = nn.Identity()

        # Optional freezing
        if freeze_backbone:
            for param in self.backbone.parameters():
                param.requires_grad = False

        # Projection layer (aligns with text embedding size)
        self.projection = nn.Sequential(
            nn.Linear(self.feature_dim, proj_dim),
            nn.BatchNorm1d(proj_dim),
            nn.ReLU()
        )

    def forward(self, x):
        features = self.backbone(x)      # [B, 2048]
        projected = self.projection(features)  # [B, proj_dim]
        return projected

"""Image Classifier Definition"""

class ImageClassifier(nn.Module):
    def __init__(self, encoder, num_classes=NUM_CLASSES):
        super().__init__()
        self.encoder = encoder
        self.classifier = nn.Sequential(
          nn.Linear(256, 64),
          nn.ReLU(),
          nn.Dropout(0.2),
          nn.Linear(64, num_classes)
        )


    def forward(self, x):
        embeddings = self.encoder(x)
        logits = self.classifier(embeddings)
        return logits

"""Initialize"""

encoder = ImageEncoder(pretrained=True, freeze_backbone=True, proj_dim=256)
model = ImageClassifier(encoder).to(device)

"""Training Loop Definition: Few words on this part. Initial design was to manually freeze/unfreeze pretrained weights as demonstrated in class, however, due to considerations given to potential need to submit to TALC, such design became infeasible because the possibility of having to submit MULTIPLE jobs and having ANOTHER submission come in between our submissions and I'm unsure how it will affect the model's performance, or can the save point be even accessed correctly if a different request was processed in between. Decision: make the training/validation loop automatically time freeze/unfreeze and process the entire process in 1 submission. In between freeze/unfreeze the optimizer learning rate as well as # of transfer learning epochs will also be tuned to avoid overfit."""

def train_model(model, train_loader, val_loader, device,
                epochs=EPOCHS,               # initial # of epochs used for model initialization
                unfreeze_epoch=UNFREEZE_EPOCH,  # epoch after which the backbone is unfrozen
                initial_lr=INITIAL_LR,       # learning rate before unfreeze
                fine_tune_lr=FINE_TUNE_LR,   # learning rate after unfreeze
                save_path=SAVE_MODEL_PATH):  # file path to save best val-loss model, Saving to FILE may be required, the model will be used later in multi-modal training once combined with text portion.

    # ---- Loss ----
    criterion = nn.CrossEntropyLoss()

    # ---- Initial optimizer: AdamW ----
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=initial_lr,
        weight_decay=1e-4
    )

    train_losses, val_losses = [], []
    best_val_loss = float("inf")

    for epoch in range(epochs):

        # This is how the automatic unfreeze works, once it reaches the defined epoch, backbone unfreezes and AdamW's lr is changed to fine_tune_lr.
        if epoch == unfreeze_epoch:
            print("Unfreezing backbone...")
            for param in model.encoder.backbone.parameters():
                param.requires_grad = True # Unfreeze happens

            # Updating lr in AdamW
            optimizer = torch.optim.AdamW(
                filter(lambda p: p.requires_grad, model.parameters()),
                lr=fine_tune_lr,
                weight_decay=1e-4
            )

        #Training
        model.train()
        running_train_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad() #resets gradient between batches
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step() #Steps only after back-propagation
            running_train_loss += loss.item()
        epoch_train_loss = running_train_loss / len(train_loader) #training loss
        train_losses.append(epoch_train_loss)

        #Validation
        model.eval()
        running_val_loss = 0.0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)
                running_val_loss += loss.item()
        epoch_val_loss = running_val_loss / len(val_loader) #validation loss
        val_losses.append(epoch_val_loss)

        print(f"Epoch {epoch+1}/{epochs} " #Prints losses
              f"Train Loss: {epoch_train_loss:.4f} "
              f"Val Loss: {epoch_val_loss:.4f}")

        # Saving model with smallest val_loss
        if epoch_val_loss < best_val_loss:
            best_val_loss = epoch_val_loss
            torch.save(model.state_dict(), save_path)
            print("Saved best model.")

    return train_losses, val_losses

"""Full-filling requirements to track misclassified images(Unimodal)"""

def evaluate_and_log_errors(model, test_loader, device,
                            save_model_path=SAVE_MODEL_PATH,
                            error_log_file=MISCLASS_FILE):

    model.load_state_dict(torch.load(save_model_path))
    model.eval()

    incorrect_samples = []
    correct, total = 0, 0

    with torch.no_grad():
        for batch_idx, (images, labels) in enumerate(test_loader):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            total += labels.size(0) #Automatic resizing
            correct += (preds == labels).sum().item()

            # Log misclassified images
            for i in range(len(labels)):
                if preds[i] != labels[i]:
                    dataset_index = batch_idx * test_loader.batch_size + i
                    path, _ = test_loader.dataset.samples[dataset_index]
                    incorrect_samples.append(
                        f"{path} | Pred: {preds[i].item()} | True: {labels[i].item()}"
                    )

    accuracy = correct / total
    print(f"Test Accuracy: {accuracy:.4f}")

    with open(error_log_file, "w") as f:
        for line in incorrect_samples:
            f.write(line + "\n")
    print(f"Misclassified samples written to {error_log_file}")
    return accuracy

"""Loss Curve"""

def plot_losses(train_losses, val_losses, save_path=LOSS_PLOT_PATH):
    plt.figure()
    plt.plot(train_losses, label="Train Loss")
    plt.plot(val_losses, label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.title("Training and Validation Loss")
    plt.savefig(save_path)
    plt.close()
    print(f"Loss curve saved to {save_path}")

"""Running model"""

train_losses, val_losses = train_model(model, train_loader, val_loader, device)
plot_losses(train_losses, val_losses)
accuracy = evaluate_and_log_errors(model, test_loader, device)
imagemodel = model

"""Retrieve Image Embeddings for Fusion"""

def get_image_embeddings_batchwise(dataset, model, batch_size=16):
    """
    Extract image embeddings in batches to avoid OOM errors.
    """
    model.eval()
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    all_embeddings = []

    with torch.no_grad():
        for batch in loader:
            images, _ = batch  # ignore labels here
            images = images.to(device)
            embeddings = model.encoder(images)
            all_embeddings.append(embeddings.cpu())

    return torch.cat(all_embeddings, dim=0).numpy()

# Distill-Bert Text Classification

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, DistilBertForSequenceClassification
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""Tokenizer+Model"""

MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
base_model = AutoModel.from_pretrained(MODEL_NAME)

base_model = base_model.to(device)

"""Data Extraction"""

import os
import re
import numpy as np

def read_text_files_with_labels(path):
    texts = []
    labels = []

    class_folders = sorted([
    f for f in os.listdir(path)
    if os.path.isdir(os.path.join(path, f)) and not f.startswith(".")
]) #Avoids hidden files being picked up

    label_map = {class_name: idx for idx, class_name in enumerate(class_folders)}

    for class_name in class_folders:
        class_path = os.path.join(path, class_name)

        if os.path.isdir(class_path):
            file_names = sorted(os.listdir(class_path))

            for file_name in file_names:
                file_path = os.path.join(class_path, file_name)

                if os.path.isfile(file_path):
                    # Remove extension
                    file_name_no_ext, _ = os.path.splitext(file_name)

                    # Replace "_" with space
                    text = file_name_no_ext.replace('_', ' ')

                    # Remove digits
                    text_without_digits = re.sub(r'\d+', '', text)

                    texts.append(text_without_digits)
                    labels.append(label_map[class_name])

    return np.array(texts), np.array(labels)

"""Data Collection"""

DATA_ROOT = "/work/TALC/ensf617_2026w/garbage_data"

train_texts, train_labels = read_text_files_with_labels(os.path.join(DATA_ROOT, "CVPR_2024_dataset_Train"))
val_texts, val_labels = read_text_files_with_labels(os.path.join(DATA_ROOT, "CVPR_2024_dataset_Val"))
test_texts, test_labels = read_text_files_with_labels(os.path.join(DATA_ROOT, "CVPR_2024_dataset_Test"))

print("Train samples:", len(train_texts))
print("Val samples:", len(val_texts))
print("Test samples:", len(test_texts))

"""Text Dataset"""

MAX_LEN = 384

class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long),
            "text": text 
        }

"""Data-Loaders"""

BATCH_SIZE = 16

train_dataset = TextDataset(train_texts, train_labels, tokenizer)
val_dataset   = TextDataset(val_texts, val_labels, tokenizer)
test_dataset  = TextDataset(test_texts, test_labels, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE)
test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE)

"""Classification Head"""

class TextClassifier(nn.Module):
    def __init__(self, num_classes, base_model):
        super().__init__()
        self.base_model = base_model
        hidden_size = base_model.config.hidden_size
        self.fc = nn.Linear(hidden_size, num_classes)


    def forward(self, input_ids, attention_mask):
        outputs = self.base_model(input_ids=input_ids, attention_mask=attention_mask)
        # Mean pooling
        last_hidden = outputs.last_hidden_state  # (batch, seq_len, hidden_size)
        mask_expanded = attention_mask.unsqueeze(-1).expand(last_hidden.size()).float()
        sum_embeddings = torch.sum(last_hidden * mask_expanded, dim=1)
        sum_mask = torch.clamp(mask_expanded.sum(dim=1), min=1e-9)
        pooled = sum_embeddings / sum_mask  # (batch, hidden_size)
        return self.fc(pooled)

"""Model Instantiation"""

model = TextClassifier(num_classes=4, base_model=base_model).to(device)

"""Optimizer + Loss"""

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

"""Training Loop"""

EPOCHS = 10

train_losses = []
val_losses = []
misclassified_files = []

for epoch in range(EPOCHS):

    # Training

    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for batch in train_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()

        outputs = model(input_ids, attention_mask)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    train_loss = total_loss / len(train_loader)
    train_acc = correct / total
    train_losses.append(train_loss)

    # Validation

    model.eval()
    val_loss_total = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)
            file_names = batch.get("file_name", [None]*labels.size(0))  # fallback if not present

            outputs = model(input_ids, attention_mask)
            loss = criterion(outputs, labels)
            val_loss_total += loss.item()

            preds = torch.argmax(outputs, dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    val_loss = val_loss_total / len(val_loader)
    val_acc = correct / total
    val_losses.append(val_loss)

    # Logging

    print(f"Epoch {epoch+1}/{EPOCHS}")
    print(f"Train Loss: {train_loss:.4f}")
    print(f"Train Acc:  {train_acc:.4f}")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Val Acc:    {val_acc:.4f}")
    print("-" * 40)

"""Testing Block"""

device = "cuda" if torch.cuda.is_available() else "cpu"

model.eval()
all_preds = []
misclassified_texts = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        preds = outputs.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())

        # Capture misclassified samples
        mis_idx = (preds != labels).nonzero(as_tuple=True)[0]
        for idx in mis_idx:
            misclassified_texts.append(batch["text"][idx])  # assuming your dataset returns 'text'

# Compute accuracy
accuracy = (torch.tensor(all_preds) == torch.tensor(test_labels)).float().mean()
print(f"Test Accuracy: {accuracy*100:.2f}%")
print(f"Number of misclassified samples: {len(misclassified_texts)}")

"""Loss Chart"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(range(1, EPOCHS+1), train_losses, label="Train Loss")
plt.plot(range(1, EPOCHS+1), val_losses, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training & Validation Loss")
plt.legend()
plt.grid(True)
plt.savefig("/home/le.song/Assignment2/ls_chart_part2")

"""Saving Model"""

torch.save(model.state_dict(), "/home/le.song/Assignment2/clean_text_classifier.pth")



def extract_text_embeddings_batchwise(text_list, model, tokenizer, batch_size=16, max_len=MAX_LEN):
    """
    Extract text embeddings efficiently in batches.
    """
    model.eval()
    all_embeddings = []

    for i in range(0, len(text_list), batch_size):
        batch_texts = text_list[i:i+batch_size]
        encoding = tokenizer(
            batch_texts,
            padding='max_length',
            truncation=True,
            max_length=max_len,
            return_tensors='pt'
        ).to(device)

        with torch.no_grad():
            outputs = model.base_model(**encoding)
            last_hidden = outputs.last_hidden_state  # (batch, seq_len, hidden_size)
            mask_expanded = encoding['attention_mask'].unsqueeze(-1).expand(last_hidden.size()).float()
            pooled = (last_hidden * mask_expanded).sum(dim=1) / mask_expanded.sum(dim=1).clamp(min=1e-9)
            all_embeddings.append(pooled.cpu())

    return torch.cat(all_embeddings, dim=0).numpy()



# --- Extract image embeddings for all datasets ---
train_img_embeddings = get_image_embeddings_batchwise(train_dataset, imagemodel, batch_size=16)
val_img_embeddings   = get_image_embeddings_batchwise(val_dataset, imagemodel, batch_size=16)
test_img_embeddings  = get_image_embeddings_batchwise(test_dataset, imagemodel, batch_size=16)

# --- Extract text embeddings ---
# Load trained model first
text_model = TextClassifier(num_classes=4, base_model=base_model).to(device)
text_model.load_state_dict(torch.load("/home/le.song/Assignment2/clean_text_classifier.pth"))

train_text_embeddings = extract_text_embeddings_batchwise(train_texts, text_model, tokenizer, batch_size=16)
val_text_embeddings   = extract_text_embeddings_batchwise(val_texts, text_model, tokenizer, batch_size=16)
test_text_embeddings  = extract_text_embeddings_batchwise(test_texts, text_model, tokenizer, batch_size=16)

class FusionDataset(Dataset):
    def __init__(self, img_emb, text_emb, labels):
        self.img_emb = torch.tensor(img_emb, dtype=torch.float32)
        self.text_emb = torch.tensor(text_emb, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            "img_emb": self.img_emb[idx],
            "text_emb": self.text_emb[idx],
            "label": self.labels[idx]
        }

train_fusion = FusionDataset(train_img_embeddings, train_text_embeddings, train_labels)
val_fusion   = FusionDataset(val_img_embeddings, val_text_embeddings, val_labels)
test_fusion  = FusionDataset(test_img_embeddings, test_text_embeddings, test_labels)

train_loader = DataLoader(train_fusion, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_fusion, batch_size=16)
test_loader  = DataLoader(test_fusion, batch_size=16)

fusion_input_dim = train_img_embeddings.shape[1] + train_text_embeddings.shape[1]

class FusionClassifier(nn.Module):
    def __init__(self, input_dim=fusion_input_dim, hidden_dim=128, num_classes=4):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, img_emb, text_emb):
        x = torch.cat([img_emb, text_emb], dim=1)
        return self.fc(x)

fusion_model = FusionClassifier().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(fusion_model.parameters(), lr=1e-3)

FROZEN_EPOCHS = 10  # train classifier head only
FINE_TUNE_EPOCHS = 5 # unfreeze embeddings and fine-tune

# Freeze everything except FC layers initially
def freeze_backbones(model):
    for name, param in model.named_parameters():
        if "fc" not in name:
            param.requires_grad = False

def unfreeze_all(model):
    for param in model.parameters():
        param.requires_grad = True

freeze_backbones(fusion_model)

train_losses, val_losses = [], []

total_epochs = FROZEN_EPOCHS + FINE_TUNE_EPOCHS
misclassified = []
for epoch in range(total_epochs):
    if epoch == FROZEN_EPOCHS:
        print("Unfreezing all backbones for fine-tuning...")
        unfreeze_all(fusion_model)
        optimizer = torch.optim.AdamW(fusion_model.parameters(), lr=1e-5)

    # --- Training ---
    fusion_model.train()
    running_loss = 0.0
    for batch in train_loader:
        img_emb = batch["img_emb"].to(device)
        text_emb = batch["text_emb"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()
        outputs = fusion_model(img_emb, text_emb)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    train_loss = running_loss / len(train_loader)
    train_losses.append(train_loss)

    # --- Validation ---
    fusion_model.eval()
    running_val_loss = 0.0
    correct, total = 0, 0
    with torch.no_grad():
        for batch in val_loader:
            img_emb = batch["img_emb"].to(device)
            text_emb = batch["text_emb"].to(device)
            labels = batch["label"].to(device)

            outputs = fusion_model(img_emb, text_emb)
            loss = criterion(outputs, labels)
            running_val_loss += loss.item()

            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            # Capture misclassifications
            for i in range(len(labels)):
                if preds[i] != labels[i]:
                    misclassified.append(i)  # you can map to original files if needed

    val_loss = running_val_loss / len(val_loader)
    val_acc = correct / total
    val_losses.append(val_loss)

    print(f"Epoch {epoch+1}/{total_epochs} Train Loss: {train_loss:.4f} Val Loss: {val_loss:.4f} Val Acc: {val_acc:.4f}")

    # Save best model (or final one)
torch.save(fusion_model.state_dict(), "/home/le.song/Assignment2/fusion_model.pth")

# Loss plot
plt.figure()
plt.plot(range(1, total_epochs+1), train_losses, label="Train Loss")
plt.plot(range(1, total_epochs+1), val_losses, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Fusion Training Loss")
plt.savefig("/home/le.song/Assignment2/fusion_loss_curve.png")
plt.close()

# Misclassified log
with open("/home/le.song/Assignment2/fusion_misclassified.txt", "w") as f:
    for idx in misclassified:
        f.write(f"{idx}\n")  # or map idx to file name/text if you like